CMakeLists.txt, src/GameSrc/olh.c, src/GameSrc/textmaps.c
Actually this should be SDL2_INCLUDE_DIRS, not SDL2_INCLUDE_DIR
=> Fix SDL2_INCLUDE_DIRS variable in CMakeLists

CMakeLists.txt
Adding option to control compilation of Test and Example applications.
=> ENABLE_EXAMPLE

src/Libraries/3D/Source/matrix.c
When calculating the view pyramid vector the game tries to divide all
three components by one whose magnitude is at least 0x8000. If all three
components are below this threshold it ends up dividing by the last one,
which may be very close to zero.
To avoid a floating point exception, always divide by the longest of
the three components.
=> Fix division by zero calculating pyramid vectors

src/GameSrc/Headers/setup.h, src/GameSrc/hkeyfunc.c, src/GameSrc/init.c, src/GameSrc/input.c, src/GameSrc/mainloop.c, src/GameSrc/setup.c, src/Libraries/2D/Source/strscl.c, src/Libraries/INPUT/Source/kbcook.c, src/MacSrc/Shock.c
Caveats:
- Splash screen graphics still need to be found
- Can't go from the game back to the menu yet
=> Basic main menu support

build_deps.sh, externals/findsdl2-cmake/FindSDL2.cmake, externals/findsdl2-cmake/FindSDL2_mixer.cmake
This should make building SDL not overwrite the currently installed SDL
=> Building SDL and SDL_mixer into their own directories

CMakeLists.txt, src/Libraries/CMakeLists.txt, src/Libraries/LG/Source/LOG/LICENSE, src/Libraries/LG/Source/LOG/README.md, src/Libraries/LG/Source/LOG/src/log.c, src/Libraries/LG/Source/LOG/src/log.h, src/Libraries/LG/Source/dbg.h, src/MacSrc/InitMac.c, src/MacSrc/Shock.c
Used rx/log.c https://github.com/rxi/log.c as base.
Now we can use LOGGER(level, ...) as function for logging. Fixes #37.
=> Implementing logger framework (#37)

src/GameSrc/Headers/popups.h, src/GameSrc/email.c, src/GameSrc/popups.c
=> Fix issue #67

CMakeLists.txt, src/Libraries/AFILE/Source/afile.c, src/Libraries/AFILE/Source/afile.h, src/Libraries/AFILE/Source/amov.c, src/Libraries/AFILE/Source/circbuff.h, src/Libraries/AFILE/Source/compose.c, src/Libraries/AFILE/Source/compose.h, src/Libraries/AFILE/Source/movie.h, src/Libraries/AFILE/Tests/playmov.c, src/Libraries/LG/Source/dbg.h
Not yet ready to use in Engine, but ready to play some files.
=> Restored Audio playback in AFILE

src/GameSrc/Headers/musicai.h, src/GameSrc/digifx.c, src/GameSrc/input.c, src/GameSrc/wrapper.c, src/Libraries/SND/Source/lgsndx.h, src/MacSrc/MacTune.h, src/MacSrc/Prefs.c, src/MacSrc/Prefs.h, src/MacSrc/SDLSound.c
- Add new preferences: `music-volume`, `sfx-volume` and `alog-volume`
- Resurrect sliders in `wrapper.c`
=> Enable music and SFX volume control

README.md
Some more visibility to the Windows distributables
=> First draft of a separate "Downloads" section in readme.md

appveyor.yml
Add some comments to the file to make future edits a bit easier.
=> AppVeyor config, part 2

src/GameSrc/wrapper.c
Now you get the YES | NO dialog if you want to Quit
Error:
=> Fixed Exception thrown when selecting QUIT in the in-game menu

appveyor.yml
This should fix https://github.com/Interrupt/systemshock/issues/102
=> Use 32-bit version of libstdc++ found in minGW

src/GameSrc/mouselook.c
99% of the time it works every time.
=> WIP: Fix for the "Click-for-Options cursor is displayed instead of crosshair" when pressing F bug

src/GameSrc/mouselook.c
Now it works all the time every time.
=> Better fix for the "Click-for-Options cursor is displayed instead of crosshair" when pressing F bug

README.md, osx-linux/readme_osx_linux.md, readme/readme-linux.txt, readme/readme-osx.txt, readme/readme-windows.txt
- Copy intro text from readme.md to platform specific readmes
- Improve appearance of Linux/OSX distributable readme.md
- Switch things around in main readme.md as CI systems are now in place, and the assets are a common prerequisite to everyone
=> Improve readme files

.travis.yml, build.bat
Travis offers two CPU cores, use both of them when building systemshock
=> Use two make jobs to build systemshock

src/GameSrc/cutsloop.c, src/Libraries/AFILE/Source/amov.c, src/Libraries/AFILE/Source/draw4x4.cpp, src/Libraries/AFILE/Source/draw4x4.h, src/Libraries/AFILE/Source/huff.h, src/Libraries/AFILE/Source/huffde.cpp, src/Libraries/CMakeLists.txt, src/Libraries/RES/Source/resfile.c, src/MacSrc/Shock.c
This is starting to play back the SVGA cutscenes stored in the `svgaintr.res`, `svgadeth.res` and `svgaend.res` files.
=> SVGA movie cutscenes with sound

src/MacSrc/Modding.c, src/MacSrc/Shock.c, src/MacSrc/Shock.h
Because the new fades take forever!
=> Added a '-nosplash' startup arg to skip the splash screens

src/Libraries/2D/Source/Flat8/fl8nl.c
Logic of this function allowed divide by zero in rare circumstances.
=> Check for divide by zero

src/Libraries/AFILE/Source/afile.c, src/Libraries/AFILE/Source/afile.h, src/Libraries/AFILE/Source/amov.c, src/Libraries/AFILE/Source/movie.c
Also add silence to fill block at end of email/audiologs.
=> No longer need .temp.audio file.

src/GameSrc/mouselook.c, src/Libraries/INPUT/Source/sdl_events.c, src/MacSrc/Shock.c
Use SDL's relative mouse mode instead of grabbing window.
=> Relative mouse mode

src/GameSrc/setup.c, src/GameSrc/trigger.c
Could use some tweaking on text positioning, but it's a start.
Also added win stats. Win stats and credits triggered after win movie.
=> Reverse-engineered credits display

src/GameSrc/cutsloop.c, src/Libraries/AFILE/Source/amov.c
Assigns unused palette color in current frame to subtitles.
=> Cutscene subtitles

src/GameSrc/setup.c
Resource reports bitmap as 320x320, should be 320x200
=> Fix Continue bitmap missized crash

src/GameSrc/cutsloop.c
Fix corrupt pixels at bottom of movie
=> Fix cutscene corruption, memory leaks

src/GameSrc/wrapper.c, src/MacSrc/Prefs.c
Fix onscreen help toggle button text so it shows correct current setting.
Save/load onscreen help and gamma settings in prefs file.
=> Fix onscreen help toggle button text, save/load in prefs

src/GameSrc/trigger.c
=> Limit simultaneous force bridge sfx on lev 4

src/GameSrc/audiolog.c, src/GameSrc/cutsloop.c, src/GameSrc/hkeyfunc.c, src/MacSrc/SDLSound.c, src/MacSrc/Xmi.c
Convert and stream chunks of cutscene audio instead of converting it all at once.
Audiologs stream the same way. Commits done.
=> Stream cutscene audio

src/MacSrc/SDLSound.c, src/MacSrc/Xmi.c, src/MacSrc/Xmi.h
Modify volume in music callback function according to global music volume.
=> Callback music volume

src/GameSrc/frutil.c
Check bounds and return 0 if outside
=> Prevent out-of-bounds read in fr_get_real()

src/GameSrc/biohelp.c, src/GameSrc/fullscrn.c, src/GameSrc/input.c, src/GameSrc/invent.c, src/GameSrc/screen.c, src/GameSrc/weapons.c
Also fix cursor-related crashes when changing screen resolution combined with entering/exiting cyberspace.
=> Fix motion cursor color for weapon

src/GameSrc/hkeyfunc.c
Fill out weapon struct
Limit go-to-level range
=> Crash-proof cheat commands

src/GameSrc/weapons.c, src/Libraries/INPUT/Source/sdl_events.c
=> Get weapon recoil cursor chaos working

src/GameSrc/tools.c
Prevents white pixels from accumulating at bottom of message rectangle
=> Fix messages leave white pixels behind

src/GameSrc/cutsloop.c, src/GameSrc/palfx.c
Also sync fade rate with ticks elapsed
=> Pause and fade to black at end of cutscenes

appveyor.yml, build_deps.sh, build_windows.sh, osx-linux/install_32bit_sdl.sh
Apply patch to fix voc magic
This should fix #243, but it might not, as it is untested.
=> Use SDL2_mixer 2.0.2 with backport 

src/Libraries/EDMS/Source/MODELS/bip_skel.cc, src/Libraries/EDMS/Source/MODELS/biped.cc, src/Libraries/EDMS/Source/MODELS/biped.h, src/Libraries/EDMS/Source/MODELS/bipface.cc, src/Libraries/EDMS/Source/MODELS/cr_biped.cc, src/Libraries/EDMS/Source/MODELS/death.cc, src/Libraries/EDMS/Source/MODELS/death.h, src/Libraries/EDMS/Source/MODELS/fodeath.cc, src/Libraries/EDMS/Source/MODELS/marbface.cc, src/Libraries/EDMS/Source/MODELS/marble.cc, src/Libraries/EDMS/Source/MODELS/marble.h
Restoring previously deleted unused files from EDMS.
These files are not used by Shockolate anymore and left here for historical purpose.
=> [EDMS] Restore old files

src/GameSrc/objuse.c
=> Fix vanishing elevator objects

src/GameSrc/newai.c
=> Check for gt max roam tries always fails

src/MacSrc/Xmi.c
Now music threads are logical and all handled in MyThread()
=> Do music processing on one physical thread

src/MacSrc/OpenGL.cc
bm ptr is used as hash to lookup a texture, but some textures may have the same bm ptr but different size; so include w,h in hash. Ptr part of hash must be 32 bits; w,h part 16 bits each.
This fixes texture corruption at bottom of invisible mutants on level 3.
=> Cached textures can have same bm ptr but diff w,h

src/GameSrc/wrapper.c
Allows immediate changes to be seen in OpenGL mode.
=> Render 3d view when using gamma slider

src/GameSrc/wrapper.c, src/MacSrc/Prefs.c, src/MacSrc/Prefs.h, src/MacSrc/Xmi.c, src/MacSrc/Xmi.h
This just adds the ability to change the current midi decoder from the options menu.
=> Add midi decoder option

src/GameSrc/mouselook.c, src/GameSrc/wrapper.c, src/MacSrc/Prefs.c, src/MacSrc/Prefs.h
Fixes issue #290
Changes:
- mouselook.c:
- control mouselook Y-axis behavior based on goInvertMouseY pref
- wrapper.c:
- add input menu button to display current state & allow toggle of goInvertMouseY pref
- Prefs.c, Prefs.h:
- add bool goInvertMouseY pref (default false)
=> implement option to invert mouselook Y-axis

.travis.yml, osx-linux/install_32bit_sdl.sh
Let's see if Travis likes this version of the scripts better
=> Always create lib/ directory on OSX/Linux

.travis.yml, CMakeLists.txt, README.md
Most options are now configurable during cmake invocation. You can define bundled or system libraries or disable feature completely (ON/BUNDLED/OFF tristate options).
=> Cmake improvements

src/GameSrc/Headers/precompiled.h, src/GameSrc/gamestrn.c, src/GameSrc/hkeyfunc.c, src/GameSrc/input.c, src/GameSrc/objuse.c, src/GameSrc/olh.c, src/Libraries/CMakeLists.txt
Custom lg_sprintf() now replaced by system sprintf().
=> Replace lg_sprintf() with system sprintf()

src/MacSrc/Shock.c
=> set initial window to pref size

build_win32.sh, build_win64.sh
fix .sh aborts because it can't find cmake
=> add path to cmake

src/GameSrc/Headers/setploop.h, src/GameSrc/cutsloop.c, src/GameSrc/setup.c
This should allow the "SHLINK" version of the demo to run, since its file layout is compatible with EE. The original DOS demo will need some file rearrangement.
=> Demo support

src/Libraries/RES/Source/resfile.c
Fixes https://github.com/Interrupt/systemshock/issues/357
=> Fixing savegames growing entries out of control

.travis.yml
looking ok? can this be tested if it works as intended, maybe with another pre-release? Thanks!
=> add source tarball to Travis for deployment
