- CMakeLists.txt
- src/GameSrc/objsim.c
- src/GameSrc/textmaps.c
- src/Libraries/CMakeLists.txt
- src/Libraries/FIX/Tests/FixTest/fixtest.c
- src/Libraries/RES/Source/res.h
- src/Libraries/RES/Source/resfile.c
- src/stubs/Carbon/carbon_stubs.c
For some reason the tests weren't linked against the Carbon stubs anymore so they failed to build.
Also, since replacing a few more `fopen()` with `fopen_caseless()` I can actually play a bit further until it crashed :-)
Please don't use plain `fopen()` for the regular game assets (`res/data/...`) - Linux is case sensitive, and some people (like me) have the game data in fullcaps paths
> Some Linux fixes

- externals/findsdl2-cmake/FindSDL2_mixer.cmake
- src/Libraries/RES/Source/resfile.c
- src/stubs/Carbon/carbon_stubs.c
The two #include statements help appease the fickle MinGW gods. 
I also added an improvement to the SDL2_mixer finder.
> A few changes to keep the executable compiling on MinGW

- src/GameSrc/newmfd.c
When pressing side buttons on MFD, there should be panning sound on left
or right channel, but instead of that game SEGFAULTing since ssp not
initialized.
> Commenting out SEGFAULT

- src/GameSrc/Headers/drugs.h
- src/GameSrc/cyber.c
- src/GameSrc/drugs.c
- src/GameSrc/gamewrap.c
Fixed crash when Berserk patch wearoff, fixed 'assignment makes integer from pointer without a cast
[-Wint-conversion]' warnings.
> Fixes to drugs.c

- src/GameSrc/amaploop.c
- src/GameSrc/fullamap.c
1. Instead of hardcoding a 640x480 canvas size, use the resolution of
the current screen canvas
2. Use 'svga_screen' instead of 'cit_screen' for the automap loop, as
only the former is resized in change_svga_screen_mode()
fixes #20
> Adapt full-screen automap to display resolution

- .clang-format
To use it, run `clang-format -i -style=file <file>` inside project directory.
Based on llvm style with tuning:
* ColumnLimit: 120
* AlignEscapedNewlines: Left
* IndentWidth: 4
> clang-format file (#32)

- src/Libraries/2D/Source/MacDev.c
- src/Libraries/INPUT/Source/mouse.c
- src/Libraries/INPUT/Source/sdl_events.c
- src/MacSrc/Shock.c
1. Use SDL_Renderer to blit the draw surface onto the screen
2. Make the game window resizable
3. Move mouse_get_xy() and mouse_put_xy() from mouse.c to sdl_events.c;
in the latter function, scale from game coordinates to window
coordinates
4. Implement Alt+Enter hotkey to toggle fullscreen mode
> Make game window resizable, implement fullscreen mode

- src/GameSrc/tools.c
- src/MacSrc/Shock.c
- Enable VSync when creating the SDL renderer instance
- Adapt the timing of the HUD rectangle zoom animation
Fixes #24
> Enable vertical sync

- src/GameSrc/gamesort.c
The algorithm for sorting objects to determine draw order uses three
local variables holding the camera position, and expects them to be in
subsequent memory locations. Apparently the Mac developers ran into an
issue with their compiler placing the variables in reverse order and
"fixed" it by swapping the declaration order.
Use a portable expression to get the right coordinate instead of relying
on compiler interals. This fixes an issue with a control pedestal being
visible through an opaque bridge right at the beginning of the game when
compiling with gcc.
> Fix drawing order of two-dimensional objects

- src/GameSrc/amaploop.c
When editing a map note, all key events are handled twice: once when
pressing and once when releasing the key.
> Fix double key events when editing a map note

- src/GameSrc/Headers/mainloop.h
- src/GameSrc/damage.c
- src/GameSrc/gamesys.c
- src/GameSrc/mainloop.c
- src/GameSrc/setup.c
- src/MacSrc/Shock.c
This revives the `mainloop` function inside `mainloops.c` and makes it so that death switches back over to the main menu screen instead of just quitting.
> Unifying game loops, death sends you back to the main menu

- src/Libraries/2D/Source/Flat8/fl8lnop.c
Bug description: crash potential when texture V coordinate is negative.
```
/* converts the floor of n to an integer. */
#define fix_fint(n) ((n) >> 16)
k = t_vtab[fix_fint(v)] + fix_fint(u);
if (k = t_bits[k])
*p_dest = t_clut[k];
```
What happens here is that because negative numbers actually look like really large positive numbers (-1 looks like 0xFFFFFFFF etc.), `fix_fint` converts small negative values of `v` into 0xFFFF, and whatever junk happens to be at `t_vtab[0xFFFF]` then becomes the **index** of `t_bits` that the code reads. Whenever this index happens to be broken enough, the game crashes.
Fix: prevent negative values of `v`.
> Add checks to prevent texture map overflow

- src/GameSrc/gamestrn.c
- src/GameSrc/wrapper.c
- src/MacSrc/Prefs.c
- src/MacSrc/Prefs.h
- src/MacSrc/Shock.c
Save a few configuration options (most notably: screen resolution and
language) into a global configuration file. Instead of saving to a
binary resource file (as the Mac version did), just write a super-simple
and easily extensible text file.
> Implement persistent preferences

- src/Libraries/INPUT/Source/sdl_events.c
The 'buttons' field in mouse events should contain a bitmask of the
currently pressed mouse buttons, not the button that triggered an event.
Most code doesn't care about the field, but some exotic stuff like the
slider widget in wrapper.c relies on it.
> Set correct button state in mouse events

- src/MacSrc/Shock.c
When opening the game window, set the initial size to 320x200 to match
the default value of 'convert_use_mode'. This fixes startup at the
lowest resolution setting, because change_svga_screen_mode() will not
resize the window if the old and new mode ID are equal.
Fixes #65
> Set initial window size to 320x200

- src/GameSrc/hkeyfunc.c
- src/GameSrc/input.c
- src/GameSrc/musicai.c
- src/GameSrc/olh.c
- src/GameSrc/trigger.c
- src/GameSrc/wrapper.c
- src/MacSrc/Prefs.c
- src/MacSrc/Prefs.h
- src/MacSrc/Shock.c
No longer needed since we store preferences as plain text.
> Cleanup: Remove resID parameter from Load/SavePrefs()

- src/GameSrc/biohelp.c
Commit aacce6aea introduced a wrong redefinition of NUM_BIO_TRACKS that
evaluates to zero. Using the original value from status.h makes the
waveform toggle buttons reappear.
> Resurrect bio monitor controls

- src/GameSrc/physics.c
When touching an energy drain mine the physics engine tries to play a
sound effect for each frame. This quickly exceeds the maximum number of
sound channels and causes a noticable frame rate drop.
Fixes #71
> Avoid slowdown when touching energy drain mine

- .travis.yml
- README.md
- build_deps.sh
- externals/findsdl2-cmake/FindSDL2.cmake
- externals/findsdl2-cmake/FindSDL2_mixer.cmake
Hi, 
regarding the issue #51 I made Travis CI build for MacOS and Linux. 
Build uses both clang and gcc compilers. 
I cherry-picked commits from PR #84 to make Mac version compile without errors.
I added also Travis build badge to `README.md` to indicate the current build status. 
Currently the badge points to my fork and it should be update to point this repository if this PR is accepted.
> Travis build

- appveyor.yml
- build.bat
- build_windows.sh
Relates to https://github.com/Interrupt/systemshock/issues/51.
Necessary steps after merging:
1. Create an AppVeyor account and link it to GitHub, set up this project for AppVeyor
2. Create an auth token for the project at https://github.com/settings/tokens with repo permissions
3. Encrypt the auth token value using https://ci.appveyor.com/tools/encrypt
4. Replace the auth token value in `appveyor.yml` with the encrypted value.
Optional, but nice, steps:
5. Remove `appveyor-config` from `branches` list in `appveyor.yml`
6. Opt out of global email notifications at https://ci.appveyor.com/notifications
There's probably a lot of room for improvement here; this is intentionally a bare-bones setup. Setting up tagged releases (either instead of, or in addition to, master commits) would be an …
> First Appveyor config

- .travis.yml
- osx-linux/install_32bit_sdl.sh
- osx-linux/readme_osx_linux.md
Regarding issue the #51 
I made deploy script for Travis CI. Deploy produces stand-alone executable, end user readme and SDL install script. SDL install script installs 32bit SDL2 and SDL2_mixer under user's `/usr/local`. I didn't find any public sites which provides precompiled version of 32bit SDL2 so I had to make custom install script for it. SDL install script is also pretty naive and it doesn't succeed for example if required C-libraries or C-compiler aren't installed.
There's also small `readme_osx_linux.md` for linux/osx end users for getting started.
MacOS version works fine, but I didn't get Linux version running with Virtualbox. I guess it's because of Ubuntu's display drivers or virtualbox settings. Maybe some one can verify does Linux version works on real hardware. I also …
> Add deploy section to travis build

- README.md
- src/GameSrc/audiolog.c
- src/Libraries/AFILE/Source/movie.c
- src/Libraries/SND/Source/lgsndx.h
- src/MacSrc/SDLSound.c
This plays back audiologs now, we might want to use SDL_AudioStream to do this instead to start playing the audiolog without having to load the whole thing though.
> Playing back audiologs

- .gitignore
- src/Libraries/AFILE/Source/movie.c
`tmpfile()` produces a file name that Windows can't write into without admin rights
> Change naming of temporary audio file 

- src/GameSrc/objsim.c
Texture maps with text written on them were originally drawn with
background color 0x00 (black); a hack with unknown purpose changed this
to 0xFF (a shade of yellow).
We fix up the game palette to draw 0xFF as black, too, but not the
shading table. If the surface is lighted the color is still mapped to a
darker shade of yellow.
> Fix background of computer screens with text

- src/GameSrc/digifx.c
- src/MacSrc/SDLSound.c
Elevator semaphores should be freed when the sound sample is stopped. Two bugs prevented this from happening, causing elevator semaphores to leak.
The bridge level uses a lot of elevators in the room with the first force field panel. After this room there was a high likelyhood that all semaphores were busy and no further elevators could be scheduled. These commits should fix #72 for good.
> Fix leaking elevator semaphores

- src/MacSrc/Prefs.c
- src/MacSrc/Prefs.h
- src/MacSrc/Shock.c
Restricting the mouse pointer to the game window is bothersome during
development: If the game hits a breakpoint while playing the mouse is
captured and can't be released.
This adds a "capture-mouse" preference controlling this behavior.
Currently it can only be controlled by editing the config file.
> Add preference whether to capture mouse or not

- appveyor.yml
This resumes caching of `build_ext` now that GLEW has been built there, and also adds GLEW's DLL file to the distributable package.
> Post-OpenGL additions to appveyor.yml

- src/GameSrc/audiolog.c
- src/GameSrc/digifx.c
- src/GameSrc/wrapper.c
- src/MacSrc/SDLSound.c
This fixes the bug that the Digital FX slider affects both sound effects and audio logs, and the audio logs slider does nothing. 
Also, it IMO improves the balance between music and audio log volume. Please test to see if you agree.
Please also check to see if the music volume slider acts as a master volume, as it seems to do on Windows.
> [WIP] Sound volume levels

- src/GameSrc/star.c
- src/MacSrc/OpenGL.cc
- src/MacSrc/OpenGL.h
- OpenGL ES 2.0 does't do any filtering of points by default, so this uses a shader to do a similar thing.
- Also makes stars render as crisp pixels in smaller resolutions.
- Fixes the star scaling issue seen in some places, but they still disappear sometimes
> Opengl: stars render more like in software mode

- shaders/texture.frag
- src/MacSrc/OpenGL.cc
When the night sight hardware is enabled, let the shader draw everything at full light level and in black and white.
There are a few noticeable differences compared to the software renderer:
- The original effect is more blueish. We could approximate the parameters experimentally, or try to recalculate them from the shading table.
- Software night sight suppresses all palette effects (blinking lights on textures or objects, etc.).
- With software night sight, stars become invisible through structured windows (like the grove ceilings). I think that's a bug, because simple windows continue to show stars.
Fixes #135
> Implement night sight hardware effect with OpenGL

- src/GameSrc/view360.c
- src/MacSrc/OpenGL.cc
- src/MacSrc/OpenGL.h
This fixes the Sensaround V1 hardware, by rendering just that version in software mode. Sensaround V1 must not be hardware accelerated like the upgrade are :)
> OpenGL: Rendering sensaround v1 hardware in software mode

- shaders/color.frag
- shaders/main.vert
- shaders/star.frag
- src/MacSrc/OpenGL.cc
Instead of creating an 1x1 pixel dummy texture for each polygon, simply
pass the color as a vertex attribute to the shader program.
> More efficient OpenGL polygon rendering

- src/GameSrc/tools.c
As discussed on Discord, the game segfaults with the following backtrace on my Fedora 28 machine after showing the Origin splash screen:
> 0xf7939dd1 in memcpy () from /lib/libc.so.6 (gdb) bt 
> #0 0xf7939dd1 in memcpy () from /lib/libc.so.6 
> #1 0x080f2d6c in gr_set_pal () 
> #2 0x08128ba1 in palette_advance_effect () 
> #3 0x080b1a5b in finish_pal_effect () #4 0x080c243c in draw_full_res_bm () 
> #5 0x080bbb13 in splash_draw () 
> #6 0x08078f9f in main ()
> Fix segfault before splash fade out

- src/GameSrc/trigger.c
Turn object trigger was dividing by zero.
> Fix dbl-clicking on pedestal in grove crash

- src/Libraries/2D/Source/Flat8/fl8lf.c
Floor/ceiling horizontal span drawing was occasionally spilling over by one pixel. For example, a vertical line of pixels from a floor on the player's right would appear on the left edge of the screen.
The rightmost pixel of a span sometimes went outside bounds of texture, causing corruption.
Also more strict checking for divide by zero, and cleanup of function.
> Fix floor texture map corruption

- src/GameSrc/textmaps.c
Typo due to similarity in array names. Since these arrays are different sizes, could go out of bounds and cause crash.
Crash occurred when switching levels in elevator.
> Crash in load small texturemaps

- src/Libraries/AFILE/Source/afile.c
Cause of bottom of cutscene bmp pixel corruption
> Bitmap uncompress malloc'ed space too small

- src/GameSrc/mouselook.c
which I broke with relative mouse mode.
I didn't realize glob vars mlook_vel_x & y were read in physics.c and declared in mouselook.h.
> Fix cyberspace mouselook

- src/GameSrc/amaploop.c
- src/GameSrc/fullamap.c
Symptoms: NSWE buttons and scrolling keys weren't working.
Code that checks which NSWE button pressed was faulty. Input polling was limited to mouse movements and not clicking. This caused scrolling function to not be called when clicking.
Keys weren't working because function that scrolls map was returning before actually checking keys.
Working keys made map jump because time elapsed calculation was not limited.
Map can be scrolled with cursor or numeric keypad keys.
> Fix automap scrolling

- src/GameSrc/gameobj.c
If animated screens on walls don't load for whatever reason, showobj() still tries to draw them with a null ptr, causing a crash. 9 out of 10 players agree, no screen is better than crash.
> Fix instances of null ptr deref in showobj()

- src/GameSrc/tools.c
Fixes music lapse and gives smoother animation
> Call tight_loop() in zoom_rect()

- src/GameSrc/Headers/movekeys.h
- src/GameSrc/input.c
- src/GameSrc/movekeys.c
- src/Libraries/INPUT/Source/kbcook.c
- src/Libraries/INPUT/Source/sdl_events.c
- src/MacSrc/Prefs.c
- src/MacSrc/Shock.c
On run, if it doesn't already exist, a default "keybinds.txt" file will be created next to "prefs.txt" (see Prefs.h).
Keybinds file can be edited to bind keys to hotkey, fire or move actions. Key bindings take effect on next run.
movekeys.c was rewritten and is now much clearer.
If for some reason keybinds file cannot be read, default keys will still be properly set.
Also added/fixed:
Use SDL_TEXTINPUT events for printable char keys
Fix ALT key not working
Fix save hotkey
Quit hotkey was quitting without confirmation (!)
Fix randomly dropped modified keys (aka insidious evil)
Commits done.
> Implement user-definable keys

- src/GameSrc/gameobj.c
Some tiles are drawn without a texture map (such as a forcefield), so it would be null.
But sometimes this function expects a bmp and gets null, which was causing my crash.
> Fix colored forcefields not displaying

- src/GameSrc/gameobj.c
Crash setup:
Load a save game just before entering cyberspace to fight shodan.
Win or lose game and return to menu.
Load save game in west elevator on level 2.
Walk into the hallway near the animated screens in the room full of bodies.
As soon as the game tries to render the screens the game crashes.
What happens is that in show_obj() the animated screen texture tries to load but fails (there is a message in the console). I can't find the cause, but in the meantime prevent the crash by checking for a null bitmap. The screens on the walls won't appear, though.
Exiting the program, then loading the save and walking near the screens fixes the problem. It might be related to some quirk of how resources are handled.
Edit: The screens seem to load now, or I haven't been able to reproduce the …
> Fix animated screen not loaded crash

- src/GameSrc/cutsloop.c
- src/MacSrc/Shock.c
We need some way to draw color 255 as red instead of black; then this code can be removed.
> Fix "reviving" text color in intro cutscene

- src/GameSrc/wrapper.c
detail_dealfunc changes _fr_global_detail
Detail level in player struct is not actually used.
> Fix detail level button text

- src/GameSrc/gamewrap.c
- src/GameSrc/setup.c
Fixes all kinds of problems when starting a new or loading a saved game.
Also pass along current volume of title and credits music to start_track(), even though it doesn't currently use it; left out of old PR.
> Empty slate after return to setup or when loading game

- src/GameSrc/damage.c
- src/GameSrc/setup.c
If weapon_button_up doesn't get reset (TRUE), first press of weapon button will be ignored. This is noticeable when exiting a regeneration chamber, but also belongs in empty_slate().
Also, unrelated to above, prevent skipping credits when pressing Esc at win statistics screen by waiting a few seconds before acknowledging Esc in credits.
> Reset weapon button up + Fix win Esc skips credits

- src/MacSrc/Shock.c
> Fix opengl fails to init

- src/GameSrc/input.c
- src/GameSrc/mfdgump.c
- src/GameSrc/objuse.c
- src/Libraries/INPUT/Source/sdl_events.c
Shift+leftclicking a container/body once shows contents, leaving mouselook alone. Second time puts important object on cursor then in inventory if possible, also leaving mouselook alone.
Shift+leftclicking an object like a patch or weapon puts it on cursor then in inventory if possible, leaving mouselook alone. Any weapon added this way (to an empty slot) is selected.
Shift+leftclicking something like a keypad turns mouselook off.
> Implement shift+leftclick for fast object pickup

- src/GameSrc/gamerend.c
c_ror_by_5() is an rvalue which has no effect
> Fix tv static/snow randomness

- src/GameSrc/olh.c
Apparently multiple typos
<=
NUM_HACK_CAMERAS
> Fix oob in olh candidate

- src/GameSrc/vmail.c
Keep music playing and mouse pointer moving while waiting for input at end of vmail
> Fix end of vmail music/pointer freeze

- src/GameSrc/star.c
Clipped points left over from drawing poly were being used to find std_min_z
std_min_z was not being set below its max value, which caused star_render to abort.
> Fix disappearing stars

- src/GameSrc/tools.c
- src/Libraries/2D/Source/pal.c
- src/MacSrc/Prefs.c
- src/MacSrc/Shock.c
This fixes an old problem I've been having with a too-bright screen that can't be corrected with the gamma slider.
Let me explain:
Before my last graphics driver update, the brightness was correct in windowed mode, but far too bright when switching to fullscreen. The colors also seemed to be washed out.
On the latest graphics driver, the brightness is now always too high, windowed or fullscreen. Only disabling OpenGL (stopping SDL from actually using the OpenGL driver) gets it back to what I expect it should be.
The changes in this PR fix the problem for me, as well as enforce the gamma preference for all palette changes in the game.
Edit:
Using look up table so no math is done for each palette change.
> Handle gamma pref in SetSDLPalette()

- CMakeLists.txt
Code is written for signed char, but some platforms will default unsigned.
Optimize level 3 for distributable build. Saves a few percent CPU usage on my PC.
> Compile with signed char, -O3 distributable build

- src/MacSrc/Shock.c
OpenGL does its own gamma correction; factor it in if OpenGL not used.
> Factor gamma if OpenGL not used

- shaders/texture.frag
- src/Libraries/3D/Source/Bitmap.c
- src/MacSrc/OpenGL.cc
- src/MacSrc/Shock.c
Fix software invisible mutant disappears when near; see commit comment.
Square light intensity to make dark areas dark.
Add shader code to make OpenGL invisible mutants translucent.
> sq light intensity + make mutants invis in OpenGL

- src/GameSrc/gamewrap.c
- src/GameSrc/wrapper.c
- src/MacSrc/Prefs.c
If portable.txt file exists in game folder, prefs.txt and keybinds.txt will reside with it.
Add message length (normal/terse) and audiolog setting (text/audio/both) to prefs file. Don't load audiolog setting from saved game.
Fix message length button in options setting wrong variable.
Fix ghost mouse cursor when opening settings while cursor is in settings area in full 3d mode.
>  Portable prefs option + Add more settings to prefs

- src/MacSrc/Shock.c
The #include is needed for `pow`.
> Fix building on MinGW.

- CMakeLists.txt
- README.md
- appveyor.yml
- build_deps.sh
- build_windows.sh
- osx-linux/install_32bit_sdl.sh
Update build scripts with most recent SDL and SDL mixer versions. This gets rid of the need to retrieve a patch for SDL mixer. 
As this changes the external dependencies on Windows, I'm turning off AppVeyor caching to make sure that the build succeeds on that platform. This also means that another AppVeyor cache purge and updating `appveyor.yml` to turn caching back on is needed after merging. I dug up the instructions on how to purge the cache from Discord:
```
AppVeyor uses bearer token authentication. Token can be found on API token page under your AppVeyor account.
Token must be set in Authorization header of every request to AppVeyor REST API:
Authorization: Bearer <token>
```
```
You can use AppVeyor REST API to delete build cache of specific project. Use CURL, Postman, Fiddler, …
```
> Use SDL mixer 2.0.4

- src/GameSrc/input.c
- src/Libraries/RES/Source/res.c
- src/Libraries/RES/Source/resfile.c
- src/Libraries/UI/Source/event.c
This would cause the uninitialized read at this location.
https://github.com/Interrupt/systemshock/blob/c0d6fb64a01b183f891cebf9cadcd46c4140eb4b/src/Libraries/RES/Source/resfile.c#L324
> Fix use of uninitialized memory

- CMakeLists.txt
- src/MacSrc/SDLSound.c
- src/MacSrc/Xmi.c
- src/MusicSrc/MusicDevice.c
- src/MusicSrc/MusicDevice.h
#277 
Permit music synthesis based on wavetables.
To make it work, build with FluidSynth and have a soundfont file of your choice in `res/music.sf2`.
If not present, I make it fall back on libADLMIDI as usual.
I put the source in a created directory `MusicSrc`. If this isn't right, it's possible to change as you think appropriate.
> Support MIDI music based on FluidSynth backend

- CMakeLists.txt
- appveyor.yml
- build_deps.sh
- build_windows.sh
- src/GameSrc/cutsloop.c
- src/MacSrc/SDLSound.c
- src/MacSrc/Shock.c
- src/MacSrc/Xmi.c
- src/MusicSrc/MusicDevice.c
- src/MusicSrc/MusicDevice.h
Building on top of https://github.com/Interrupt/systemshock/pull/278, this incorporates the fluidsynth-lite library into the Windows build sequence -- and tries to do so for the generic `build_deps.sh`, further testing and finetuning is probably needed there. Further, it adds the Windows default soundfont as a downloaded default resource. 
As always, a change to `build_ext` requires an Appveyor cache flush.
Note that I didn't touch `travis.yml` as I think the whole process of building the distributable there needs some love from a person with a better grasp of the Linux/OSX world. The big question is whether we should have a separate build file for those environments over the general `build_deps.sh`, and how to handle the library dependencies in general.
> Add fluidsynth-lite to Windows builds

- .gitignore
- CMakeLists.txt
- src/GameSrc/wrapper.c
- src/MusicSrc/MusicDevice.c
Implemented Linux support for native MIDI music driver, via the ALSA sequencer API.
Tested in an Ubuntu VM with various software synthesizers that provide ALSA sequencer devices (Fluidsynth via Qsynth, Timidity, Yoshimi).
> Add native MIDI support for Linux

- .travis.yml
Fix the omission of the latest additions to the Travis artifacts: the 30MB Windows-like soundfont and an experimental set of precompiled libraries. 
After this, the Linux and OSX packages should theoretically be close to being able to start up by simply executing `./run.sh`.
> Fix Travis packages

- src/GameSrc/Headers/wrapper.h
- src/GameSrc/wrapper.c
- src/MacSrc/Prefs.h
- src/MacSrc/Xmi.c
I feel this is a cleaner way of doing it. If you disagree, let me know.
> Use enums instead of defines for synth settings

- src/Libraries/INPUT/Source/sdl_events.c
Now the Shockolate mouse cursor should follow/replace the OS mouse cursor whenever the mouse points at the Shockolate window.
> Improve mouse focus logic

- src/Libraries/AFILE/Source/afile.c
- src/Libraries/AFILE/Source/amov.c
- src/Libraries/AFILE/Source/draw4x4.cpp
Fixes issue #309. Following a comment from @donnierussellii I've also removed the excessive slop from the working framebuffer, but left in some overrun detection code as a precaution.
> Fix bad pixels in intro

- CMakeLists.txt
- src/GameSrc/Headers/shockolate_version.h.in
- src/GameSrc/Headers/version.h
- src/GameSrc/Headers/version.h.in
- src/GameSrc/init.c
- src/MacSrc/InitMac.c
- src/MacSrc/Shock.c
After building executable will have nice autogenerated version like "Shockolate 0.7.8-g66e2ada" (if project built from git) or simple "Shockolate 0.7.8".
On every major update and release project version in CMakeLists.txt should be incremented. In future this information can be used for autopackaging.
> Include version and revision from project and git history

- src/Libraries/AFILE/Source/draw4x4.cpp
The previous code was adapted directly from the object code and very much x86-register based. It used 32-bit integers and pointers interchangeably and made the 64-bit compiler very unhappy. I've updated it to be 64-bit friendly.
Note that although the code is more portable, it's still not exactly readable. I could do a complete rewrite if people think it's worth it; however, although Terri Brosius has a wonderful voice, I'm not sure how many more times I can listen to her say "New Atlanta. Sector 11. Building 71-G" without going round the twist :)
> Rewrite low-level Draw4x4 routines in more portable C++ (64-bit compatibility)

- src/MacSrc/SDLSound.c
- src/MusicSrc/MusicDevice.c
- src/MusicSrc/MusicDevice.h
- sblaster for ADLMIDI
- genmidi for FluidSynth and external
The weakness of this patch is that switching the music device in game won't
trigger a reload of the music resources.
(Personally I think the genmidi resources sound a lot better than the sblaster resources on real GM devices, if only because much greater polyphony is available)
> Music:  Load the correct midi resources for the music device in use.

- src/Libraries/2D/Source/2d.h
- src/Libraries/2D/Source/ctxmac.h
- src/Libraries/2D/Source/pertyp.h
long is 64 bits on Linux but 32 bits on Windows. Some pointer values were being set via a long causing pointers to be truncated.
> Change some long to intptr_t to fix crash on 64-bit Windows.

- src/Libraries/INPUT/Source/sdl_events.c
mouse pointer visibility outside game window should occur when
game is paused (by hitting esc), in a menu (such as the main or options menus),
or when window does not have input focus
by using input focus, instead of mouse focus, this works as expected
and prevents distracting pointer visibility
> check input instead of mouse focus

- README.md
- build_win32.sh
- build_win64.sh
The Windows build scripts currently try to download CMake if it hasn't already been installed. This is kind of a bad idea because the actual game compilation still requires CMake on the PATH -- so I removed the CMake downloading function, and added a check for a CMake binary that errors out if it's not found.
Similar stuff should probably be added to the other dependency build scripts.
> Require preinstalled CMake

- src/GameSrc/mfdfunc.c
Hello. If you reload a weapon with the last clip, you will not able to unload and then load it again (the remaining ammo disappears). Also it can be rendered incorrectly in HUD (screenshot shows a railgun loaded with magcarts).
The problem is caused by incorrect check in `mfd_weapon_expose_projectile()`. A comment before that check seems to be incorrect. Tested it by swapping weapons of different type (pistol/automatic/beam) in weapon slots in all possible combinations, all seem to be OK.
> Fix the problem with weapon reload when running low on ammo

- src/MacSrc/Shock.c
Hello. I get black color rendered as transparent. This patch should fix it for both renderers (Software and OpenGL). I don't really understand how rendering is working in System Shock and this patch is made during some experiments with palette, but seems to work.
Before:
After:
> Fix rendering black color as transparent

- src/GameSrc/Headers/mouselook.h
- src/GameSrc/Headers/musicai.h
- src/GameSrc/gamestrn.c
- src/GameSrc/mouselook.c
- src/GameSrc/musicai.c
- src/GameSrc/wrapper.c
- src/Libraries/2D/Source/tlucdat.h
- src/MacSrc/MacTune.c
- src/MacSrc/MacTune.h
- src/MacSrc/Modding.c
- src/MacSrc/Modding.h
- src/MacSrc/Xmi.c
- src/MacSrc/Xmi.h
Fixes compiling and linking with gcc10 on Fedora 32.
(Declare them as externs, and properly declare/instantiate them in C files instead.  Where it's defined in more than one C file, I commented the others out..)
> Don't declare variables in headers included in multiple files.

- src/MacSrc/OpenGL.cc
If project compiled with clang, get_hdpi_scaling() cause segfault. Fixed return from int to void.
> Fix segfault in OpenGL mode

- src/Libraries/3D/Source/interp.c
va_list was assumed to be a ptr to the stack
also remove commented-out assembly and other obsolete code
> get stack parms ptr without using stdarg

- CMakeLists.32bit.txt
- CMakeLists.txt
When libevent is installed its event.h is included instead of
Library/UI's. Fix this situation by including local headers before
the headers in the system.
> Fix conflict with libevent.

- src/GameSrc/weapons.c
Without this the game would try to reload weapons that did not have ammo, which could cause it to access off the end of the player ammo clips array with strange results.
Addresses issue #384
> Added check that weapon has ammo in reload_weapon_hotkey.

- src/GameSrc/Headers/mfdext.h
- src/GameSrc/newmfd.c
- src/MacSrc/Prefs.c
On Ubuntu 20.04 and system SDL I have an issue. MFD selection do not work for left MFD. All F1..F10 keys are changing the MFD-panel on the right.
It happens because keycodes for F1..F10 much larger than 128 and interpreted as keys for right-side MFD.
Explicit selection of MFD sides and buttons is fixing this issue.
(Personally I don't use F1..F10. But I going to change game controls code so I started with this)
> explicit MFD selection

- src/GameSrc/mouselook.c
- src/Libraries/EDMS/Source/edms.h
- src/Libraries/EDMS/Source/interfac.cc
Just a re-implementation of horizontal mouse look that no longer freezes up the player's stance (leaning, crouching, etc.) while looking around.
> Mouselook stance freeze fix

- .gitignore
- src/GameSrc/setup.c
- src/Libraries/RES/Source/caseless.c
- src/MacSrc/OpenGL.cc
- src/MacSrc/OpenGL.h
- src/MacSrc/Shock.c
- src/MusicSrc/MusicDevice.c
Modifications to pull the data from Application Support in macOS in order to facilitate distribution as an App Bundle.
Also incorporated code from this unmerged PR to fix issues with OpenGL https://github.com/Interrupt/systemshock/pull/409
This is the basis for the build I have on my site. 
If there's a different/better way you'd rather I handle this let me know.
> Fixes for Mac App Bundle and OpenGL on macOS
